In [1]:
import tensorflow as tf

In [3]:
# Data 
(x_train, y_train), (x_test, y_test) = tf.keras.datasets.mnist.load_data()

11501568/11490434 [==============================] - 0s 0us/step


In [4]:
x_train.shape, y_train.shape

((60000, 28, 28), (60000,))

In [8]:
# Data Processing
# Pixel Value can be 0 - 255
import numpy as np 
alist = np.array([5, 10, 15])
alist / alist.max()

array([0.33333333, 0.66666667, 1.        ])

In [9]:
# data pre-processing 
# Normalize data 
x_train = x_train / 255.0

In [ ]:
x_train[1]

In [16]:
# Modelling 
model = tf.keras.models.Sequential()

In [17]:
# Input Layer
model.add(tf.keras.layers.Input(shape=(28, 28), name="inpLayer"))
model.add(tf.keras.layers.Flatten(name='flatLayer'))

In [18]:
# Hidden Layer
model.add(tf.keras.layers.Dense(units = 120, activation=tf.keras.activations.relu, name="hidLayer"))

In [19]:
# Output Layer 
model.add(tf.keras.layers.Dense(units = 10, activation = tf.keras.activations.softmax, name = "opLayer"))

In [20]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatLayer (Flatten)         (None, 784)               0         
                                                                 
 hidLayer (Dense)            (None, 120)               94200     
                                                                 
 opLayer (Dense)             (None, 10)                1210      
                                                                 
Total params: 95,410
Trainable params: 95,410
Non-trainable params: 0
_________________________________________________________________


In [22]:
# Param - Weights & baises .. 
# Weights - 
(784 * 120)
# Weights & Biases
(784 * 120) + 120

94200

In [23]:
(120 * 10 ) + 10

1210

In [24]:
# Feed Forward 
# Error Cal
# Back Pro
model.compile(loss=tf.keras.losses.categorical_crossentropy, 
              optimizer=tf.keras.optimizers.SGD(learning_rate=0.01), 
              metrics=["acc"])

In [25]:
# Process the output 

# image with 3 
#  0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 
#  0 | 0 | 0 | 1 | 0 | 0 | 0 | 0 | 0 | 0 |  -- 3 
#  0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 1 |  -- 9 

In [26]:
y_train # shape - 60K labels

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [27]:
y_train = tf.keras.utils.to_categorical(y_train)  # 60K images each with 10 labels

In [28]:
y_train.shape

(60000, 10)

In [29]:
y_train[0]

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.], dtype=float32)

In [30]:
y_train[1]

array([1., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)

In [31]:
y_train[2]

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.], dtype=float32)

In [34]:
# Run the model 
model.fit(x_train, y_train, epochs=10)

Epoch 1/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.3386 - acc: 0.9058
Epoch 2/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.2910 - acc: 0.9183
Epoch 3/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.2614 - acc: 0.9267
Epoch 4/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.2391 - acc: 0.9335
Epoch 5/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.2209 - acc: 0.9380
Epoch 6/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.2054 - acc: 0.9423
Epoch 7/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1917 - acc: 0.9458
Epoch 8/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1797 - acc: 0.9488
Epoch 9/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1693 - acc: 0.9526
Epoch 10/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1599 - acc: 0.9548
