In [1]:
import tensorflow as tf
import numpy as np 

In [105]:
# y = 3x + 5 
# x | y 
# 1 | 8 
# 2 | 11
# 3 | 14 
# 4 | 17
x = np.random.randint(0, 100, 20)
y = x*3 + 5 

In [106]:
x_train = x.reshape(-1, 1)
y_train = y.reshape(-1, 1)

In [107]:
x_train.shape, y_train.shape

((20, 1), (20, 1))

In [108]:
tuple(zip(x_train, y_train))

((array([19]), array([62])),
 (array([35]), array([110])),
 (array([61]), array([188])),
 (array([52]), array([161])),
 (array([98]), array([299])),
 (array([42]), array([131])),
 (array([8]), array([29])),
 (array([61]), array([188])),
 (array([8]), array([29])),
 (array([2]), array([11])),
 (array([62]), array([191])),
 (array([59]), array([182])),
 (array([77]), array([236])),
 (array([32]), array([101])),
 (array([99]), array([302])),
 (array([16]), array([53])),
 (array([64]), array([197])),
 (array([95]), array([290])),
 (array([46]), array([143])),
 (array([17]), array([56])))

In [124]:
del model
model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Input(shape=(1)))
model.add(tf.keras.layers.Dense(1, activation=tf.keras.activations.relu))
model.summary()
model.compile(tf.keras.optimizers.SGD(learning_rate=0.0005), 
              loss=tf.keras.losses.mean_squared_error, 
              metrics=tf.keras.metrics.mean_squared_error)
model.fit(x_train, y_train, epochs=100, batch_size=1, verbose=0)

Model: "sequential_29"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_29 (Dense)            (None, 1)                 2         
                                                                 
Total params: 2
Trainable params: 2
Non-trainable params: 0
_________________________________________________________________


In [115]:
# should be 3 & 5 
model.get_weights()

[array([[nan]], dtype=float32), array([nan], dtype=float32)]

In [104]:
model.predict([10])

array([[34.10361]], dtype=float32)